### ISSUE TITLE
The DOI is suppsoed to be a URL

### ISSUE THREAD

**Issue by prioux** [CorentinLabelle/cbrain-plugins-brainstorm#2]
The previous issue #1 can be closed, the structure seems correct now.

However, when I tried the descriptor with BOSH I got an error message, and it seems the DOI is incorrect. I think the value is supposed to be a full URL, not just part of the DOI.

**Comment by CorentinLabelle** [comment]
I modified the DOI so it is the full URL.

**Comment by prioux** [comment]
Okay thanks,  that being said I think my local checks were wrong and maybe that wasn't really needed, sorry. But it's fine, I'll start the integration into CBRAIN this afternoon. Your work is done. Consider closing these issues here.

**Comment by MontrealSergiy** [comment]
Hi, I think doi is not necessarily url, but when added with doi.org/... should open thing in the browser. I think the bug if any does not affect CBRAIN,
