### ISSUE TITLE
Adjustments to credits

### ISSUE THREAD

**Issue by prioux** [CorentinLabelle/cbrain-plugins-brainstorm#3]
The descriptor says "Author: Corentin Labelle". Are your really the AUTHOR OF THE TOOL? The author field is supposed to describe who created the tool. If you want to be credited as the author of the descriptor, the Boutiques specification doesn't have a field for that, but in CBRAIN we implemented a way to express this using the 'custom' section of the descriptor. For examples, browse any of the the descriptors in

https://github.com/aces/cbrain-plugins-neuro/tree/master/boutiques_descriptors

A specific example is at:

https://github.com/aces/cbrain-plugins-neuro/blob/master/boutiques_descriptors/oxford_asl.json

where we can see they say the author of the tool is `Oxford Centre for Functional MRI of the Brain (FMRIB)` but the authors of the descriptor are Safa, Darias and Natacha:

```json
    "custom": {
        "cbrain:author": [
            "Safa Sanami <s.sanami70@gmail.com>",
            "Darius Valevicius <darius.valevicius@mail.mcgill.ca>",
            "Natacha Beck <nbeck@mcin.ca>"
        ],
        "cbrain:readonly-input-files": true
    }
```

This example also shows a special flag `"cbrain:readonly-input-files"`set to `true` ; consider adding this if you know for sure that your tool doesn't modify the input files it's given in argument. That will help CBRAIN optimize stuff (avoinding copying data files in particular).

**Comment by CorentinLabelle** [comment]
I replace the tool's author to be the author of Brainstorm. I added the custom section to indicate that I created the descriptor and that the input is not modified during the execution.

**Comment by prioux** [comment]
The “author” field at the top level cannot be an array. It has to be a string.

**Comment by prioux** [comment]
Also, in your latest commit, you changed output-files to be a single object instead of an array of objects, like it was. Why? This new change is illegal, it violates the schema.

**Comment by CorentinLabelle** [comment]
The field 'output-files' was modified by mistake, it is now back to an array. I changed the field 'author' to a string (I included a link).

**Comment by prioux** [comment]
Perfect, looks good to me. Will deploy in CBRAIN now.
